yoav - wtf 4

diff --git a/.scripts/pre-commit b/.scripts/pre-commit
--- a/.scripts/pre-commit
+++ b/.scripts/pre-commit
@@ -9,23 +9,23 @@ stagedFiles=$(git diff --staged --name-only)
 # run spotless apply
 ./gradlew spotlessApply
 
-#status=$?
-#
-#if [ "$status" = 1 ] ; then
-#    echo "Static analysis found no problems."
-#     Add staged file changes to git
-#    for file in $stagedFiles; do
-#      if test -f "$file"; then
-#        git add "$file"
-#      fi
-#    done
-#    exit 0
-#else
-#    echo "---------------------------------------------------------"
-#    echo "       --------------------------------------------      "
-#    echo 1>&2 "Spotless Apply found violations it could not fix."
-#    echo "Run spotless apply in your terminal and fix the issues before trying to commit again."
-#    echo "       --------------------------------------------      "
-#    echo "---------------------------------------------------------"
-#    exit 1
-#fi
+status=$?
+
+if [ "$status" = 0 ] ; then
+    echo "Static analysis found no problems."
+     Add staged file changes to git
+    for file in $stagedFiles; do
+      if test -f "$file"; then
+        git add "$file"
+      fi
+    done
+    exit 0
+else
+    echo "---------------------------------------------------------"
+    echo "       --------------------------------------------      "
+    echo 1>&2 "Spotless Apply found violations it could not fix."
+    echo "Run spotless apply in your terminal and fix the issues before trying to commit again."
+    echo "       --------------------------------------------      "
+    echo "---------------------------------------------------------"
+    exit 1
+fi
