yoav - removed dep

diff --git a/.github/workflows/labels.yml b/.github/workflows/labels.yml
--- a/.github/workflows/labels.yml
+++ b/.github/workflows/labels.yml
@@ -24,21 +24,25 @@ jobs:
         run: |
           PR_NUMBER="${{ steps.pr-number.outputs.pr-number }}"
           LABELS=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels" | jq -r '.[].name' | tr '\n' ',')
-          
-          if [[ -n "${LABELS}" ]]; then
+          IFS=',' read -r -a labels_array <<< "${LABELS}"
+          echo "::set-output name=labels_array::${labels_array[*]}"
+
+      - name: check passed-all-tests label
+        run: |
+          labels_array=("${{ steps.labels.outputs.labels_array }}")
+          if [[ -n "${labels_array[@]}" ]]; then
             echo "Labels for the pull request:"
-            IFS=',' read -r -a labels_array <<< "${LABELS}"
             # Specify the label you want to check
             target_label="passed-all-tests"
             # Check if the target label exists in the array
-              if [[ " ${labels_array[*]} " =~ " ${target_label} " ]]; then
-                echo "Label '${target_label}' exists."
-                exit 0  # Exit with success status code
-              else
-                echo "Label '${target_label}' does not exist."
-                exit 1  # Exit with failure status code
-              fi
+            if [[ " ${labels_array[*]} " =~ " ${target_label} " ]]; then
+              echo "Label '${target_label}' exists."
+              exit 0  # Exit with success status code
             else
-              echo "No labels found for the pull request."
+              echo "Label '${target_label}' does not exist."
               exit 1  # Exit with failure status code
             fi
+          else
+            echo "No labels found for the pull request."
+            exit 1  # Exit with failure status code
+          fi
